## Vivado commands to make pins external

# make pad pins external
make_bd_pins_external \
  [get_bd_pins i_pms_top_fpga/pad_pmb_vr1_pms0_sda] \
  [get_bd_pins i_pms_top_fpga/pad_pmb_vr1_pms0_scl] \
  [get_bd_pins i_pms_top_fpga/pad_pmb_vr1_pms0_alert_n] \
  [get_bd_pins i_pms_top_fpga/pad_pmb_vr2_pms0_sda] \
  [get_bd_pins i_pms_top_fpga/pad_pmb_vr2_pms0_scl] \
  [get_bd_pins i_pms_top_fpga/pad_pmb_vr2_pms0_alert_n] \
  [get_bd_pins i_pms_top_fpga/pad_pmb_vr3_pms0_sda] \
  [get_bd_pins i_pms_top_fpga/pad_pmb_vr3_pms0_scl] \
  [get_bd_pins i_pms_top_fpga/pad_pmb_vr3_pms0_alert_n] \
  [get_bd_pins i_pms_top_fpga/pad_pmb_pol1_pms0_sda] \
  [get_bd_pins i_pms_top_fpga/pad_pmb_pol1_pms0_scl] \
  [get_bd_pins i_pms_top_fpga/pad_pmb_pol1_pms0_alert_n] \
  [get_bd_pins i_pms_top_fpga/pad_pmb_ibc_pms0_sda] \
  [get_bd_pins i_pms_top_fpga/pad_pmb_ibc_pms0_scl] \
  [get_bd_pins i_pms_top_fpga/pad_pmb_ibc_pms0_alert_n] \
  [get_bd_pins i_pms_top_fpga/pad_i2c2_pms0_sda] \
  [get_bd_pins i_pms_top_fpga/pad_i2c2_pms0_scl] \
  [get_bd_pins i_pms_top_fpga/pad_i2c2_pms0_smbalert_n] \
  [get_bd_pins i_pms_top_fpga/pad_i2c3_pms0_sda] \
  [get_bd_pins i_pms_top_fpga/pad_i2c3_pms0_scl] \
  [get_bd_pins i_pms_top_fpga/pad_i2c3_pms0_smbalert_n] \
  [get_bd_pins i_pms_top_fpga/pad_i2c4_pms0_sda] \
  [get_bd_pins i_pms_top_fpga/pad_i2c4_pms0_scl] \
  [get_bd_pins i_pms_top_fpga/pad_i2c4_pms0_smbalert_n] \
  [get_bd_pins i_pms_top_fpga/pad_i2c5_pms0_sda] \
  [get_bd_pins i_pms_top_fpga/pad_i2c5_pms0_scl] \
  [get_bd_pins i_pms_top_fpga/pad_i2c5_pms0_smbalert_n] \
  [get_bd_pins i_pms_top_fpga/pad_i2c6_pms0_slv_sda] \
  [get_bd_pins i_pms_top_fpga/pad_i2c6_pms0_slv_scl] \
  [get_bd_pins i_pms_top_fpga/pad_i2c7_pms0_sda] \
  [get_bd_pins i_pms_top_fpga/pad_i2c7_pms0_scl] \
  [get_bd_pins i_pms_top_fpga/pad_pms0_pms1_smbalert_n] \
  [get_bd_pins i_pms_top_fpga/pad_pms_avs_clk_vr1] \
  [get_bd_pins i_pms_top_fpga/pad_pms_avs_mdata_vr1] \
  [get_bd_pins i_pms_top_fpga/pad_pms_avs_sdata_vr1] \
  [get_bd_pins i_pms_top_fpga/pad_pms_avs_clk_vr2] \
  [get_bd_pins i_pms_top_fpga/pad_pms_avs_mdata_vr2] \
  [get_bd_pins i_pms_top_fpga/pad_pms_avs_sdata_vr2] \
  [get_bd_pins i_pms_top_fpga/pad_pms_avs_clk_vr3] \
  [get_bd_pins i_pms_top_fpga/pad_pms_avs_mdata_vr3] \
  [get_bd_pins i_pms_top_fpga/pad_pms_avs_sdata_vr3] \
  [get_bd_pins i_pms_top_fpga/pad_pms_avs_clk_ibc] \
  [get_bd_pins i_pms_top_fpga/pad_pms_avs_mdata_ibc] \
  [get_bd_pins i_pms_top_fpga/pad_pms_avs_sdata_ibc] \
  [get_bd_pins i_pms_top_fpga/pad_pms_bios_spi_cs0_n] \
  [get_bd_pins i_pms_top_fpga/pad_pms_bios_spi_clk] \
  [get_bd_pins i_pms_top_fpga/pad_pms_bios_spi_io0] \
  [get_bd_pins i_pms_top_fpga/pad_pms_bios_spi_io1] \
  [get_bd_pins i_pms_top_fpga/pad_pms_bios_spi_io2] \
  [get_bd_pins i_pms_top_fpga/pad_pms_bios_spi_io3] \
  [get_bd_pins i_pms_top_fpga/pad_pms0_pms1_spi_cs_n] \
  [get_bd_pins i_pms_top_fpga/pad_pms0_pms1_spi_clk] \
  [get_bd_pins i_pms_top_fpga/pad_pms0_pms1_spi_miso] \
  [get_bd_pins i_pms_top_fpga/pad_pms0_pms1_spi_mosi] \
  [get_bd_pins i_pms_top_fpga/pad_uart1_pms0_rxd] \
  [get_bd_pins i_pms_top_fpga/pad_uart1_pms0_txd] \
  [get_bd_pins i_pms_top_fpga/pad_pms0_slp_s3_n] \
  [get_bd_pins i_pms_top_fpga/pad_pms0_slp_s4_n] \
  [get_bd_pins i_pms_top_fpga/pad_pms0_slp_s5_n] \
  [get_bd_pins i_pms_top_fpga/pad_pms0_sys_reset_n] \
  [get_bd_pins i_pms_top_fpga/pad_pms0_sys_rsmrst_n] \
  [get_bd_pins i_pms_top_fpga/pad_pms0_sys_pwgd_in] \
  [get_bd_pins i_pms_top_fpga/pad_pms0_pwr_btn_n] \
  [get_bd_pins i_pms_top_fpga/pad_pms0_pwgd_out] \
  [get_bd_pins i_pms_top_fpga/pad_pms0_throttle_0] \
  [get_bd_pins i_pms_top_fpga/pad_pms0_throttle_1] \
  [get_bd_pins i_pms_top_fpga/pad_pms0_thermtrip_n] \
  [get_bd_pins i_pms_top_fpga/pad_pms0_errcode_0] \
  [get_bd_pins i_pms_top_fpga/pad_pms0_errcode_1] \
  [get_bd_pins i_pms_top_fpga/pad_pms0_errcode_2] \
  [get_bd_pins i_pms_top_fpga/pad_pms0_errcode_3] \
  [get_bd_pins i_pms_top_fpga/pad_pms0_reset_out_n] \
  [get_bd_pins i_pms_top_fpga/pad_pms0_socket_id_0] \
  [get_bd_pins i_pms_top_fpga/pad_pms0_socket_id_1] \
  [get_bd_pins i_pms_top_fpga/pad_pms0_strap_0] \
  [get_bd_pins i_pms_top_fpga/pad_pms0_strap_1] \
  [get_bd_pins i_pms_top_fpga/pad_pms0_strap_2] \
  [get_bd_pins i_pms_top_fpga/pad_pms0_strap_3] \
  [get_bd_pins i_pms_top_fpga/jtag_tms_i] \
  [get_bd_pins i_pms_top_fpga/jtag_tdi_i] \
  [get_bd_pins i_pms_top_fpga/jtag_tdo_o] \
  [get_bd_pins i_pms_top_fpga/jtag_tck_i] \
  [get_bd_pins i_pms_top_fpga/jtag_trst_i]
