// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Register Package auto-generated by `reggen` containing data structure

package scmi_reg_pkg;

  // Address widths within the block
  parameter int BlockAw = 8;

  ////////////////////////////
  // Typedefs for registers //
  ////////////////////////////

  typedef struct packed {
    logic [31:0] q;
  } scmi_reg2hw_doorbell_c0_reg_t;

  typedef struct packed {
    logic [31:0] q;
  } scmi_reg2hw_completion_interrupt_c0_reg_t;

  // Register -> HW type
  typedef struct packed {
    scmi_reg2hw_doorbell_c0_reg_t doorbell_c0; // [63:32]
    scmi_reg2hw_completion_interrupt_c0_reg_t completion_interrupt_c0; // [31:0]
  } scmi_reg2hw_t;

  // Register offsets
  parameter logic [BlockAw-1:0] SCMI_RESERVED_1_C0_OFFSET = 8'h 0;
  parameter logic [BlockAw-1:0] SCMI_CHANNEL_STATUS_C0_OFFSET = 8'h 4;
  parameter logic [BlockAw-1:0] SCMI_RESERVED_2_C0_OFFSET = 8'h 8;
  parameter logic [BlockAw-1:0] SCMI_RESERVED_3_C0_OFFSET = 8'h c;
  parameter logic [BlockAw-1:0] SCMI_CHANNEL_FLAGS_C0_OFFSET = 8'h 10;
  parameter logic [BlockAw-1:0] SCMI_LENGTH_C0_OFFSET = 8'h 14;
  parameter logic [BlockAw-1:0] SCMI_MESSAGE_HEADER_C0_OFFSET = 8'h 18;
  parameter logic [BlockAw-1:0] SCMI_MESSAGE_PAYLOAD_0_C0_OFFSET = 8'h 1c;
  parameter logic [BlockAw-1:0] SCMI_MESSAGE_PAYLOAD_1_C0_OFFSET = 8'h 20;
  parameter logic [BlockAw-1:0] SCMI_MESSAGE_PAYLOAD_2_C0_OFFSET = 8'h 24;
  parameter logic [BlockAw-1:0] SCMI_MESSAGE_PAYLOAD_3_C0_OFFSET = 8'h 28;
  parameter logic [BlockAw-1:0] SCMI_MESSAGE_PAYLOAD_4_C0_OFFSET = 8'h 2c;
  parameter logic [BlockAw-1:0] SCMI_MESSAGE_PAYLOAD_5_C0_OFFSET = 8'h 30;
  parameter logic [BlockAw-1:0] SCMI_MESSAGE_PAYLOAD_6_C0_OFFSET = 8'h 34;
  parameter logic [BlockAw-1:0] SCMI_MESSAGE_PAYLOAD_7_C0_OFFSET = 8'h 38;
  parameter logic [BlockAw-1:0] SCMI_MESSAGE_PAYLOAD_8_C0_OFFSET = 8'h 3c;
  parameter logic [BlockAw-1:0] SCMI_MESSAGE_PAYLOAD_9_C0_OFFSET = 8'h 40;
  parameter logic [BlockAw-1:0] SCMI_MESSAGE_PAYLOAD_10_C0_OFFSET = 8'h 44;
  parameter logic [BlockAw-1:0] SCMI_MESSAGE_PAYLOAD_11_C0_OFFSET = 8'h 48;
  parameter logic [BlockAw-1:0] SCMI_MESSAGE_PAYLOAD_12_C0_OFFSET = 8'h 4c;
  parameter logic [BlockAw-1:0] SCMI_MESSAGE_PAYLOAD_13_C0_OFFSET = 8'h 50;
  parameter logic [BlockAw-1:0] SCMI_MESSAGE_PAYLOAD_14_C0_OFFSET = 8'h 54;
  parameter logic [BlockAw-1:0] SCMI_MESSAGE_PAYLOAD_15_C0_OFFSET = 8'h 58;
  parameter logic [BlockAw-1:0] SCMI_MESSAGE_PAYLOAD_16_C0_OFFSET = 8'h 5c;
  parameter logic [BlockAw-1:0] SCMI_MESSAGE_PAYLOAD_17_C0_OFFSET = 8'h 60;
  parameter logic [BlockAw-1:0] SCMI_MESSAGE_PAYLOAD_18_C0_OFFSET = 8'h 64;
  parameter logic [BlockAw-1:0] SCMI_MESSAGE_PAYLOAD_19_C0_OFFSET = 8'h 68;
  parameter logic [BlockAw-1:0] SCMI_MESSAGE_PAYLOAD_20_C0_OFFSET = 8'h 6c;
  parameter logic [BlockAw-1:0] SCMI_MESSAGE_PAYLOAD_21_C0_OFFSET = 8'h 70;
  parameter logic [BlockAw-1:0] SCMI_MESSAGE_PAYLOAD_22_C0_OFFSET = 8'h 74;
  parameter logic [BlockAw-1:0] SCMI_MESSAGE_PAYLOAD_23_C0_OFFSET = 8'h 78;
  parameter logic [BlockAw-1:0] SCMI_MESSAGE_PAYLOAD_24_C0_OFFSET = 8'h 7c;
  parameter logic [BlockAw-1:0] SCMI_MESSAGE_PAYLOAD_25_C0_OFFSET = 8'h 80;
  parameter logic [BlockAw-1:0] SCMI_MESSAGE_PAYLOAD_26_C0_OFFSET = 8'h 84;
  parameter logic [BlockAw-1:0] SCMI_MESSAGE_PAYLOAD_27_C0_OFFSET = 8'h 88;
  parameter logic [BlockAw-1:0] SCMI_MESSAGE_PAYLOAD_28_C0_OFFSET = 8'h 8c;
  parameter logic [BlockAw-1:0] SCMI_MESSAGE_PAYLOAD_29_C0_OFFSET = 8'h 90;
  parameter logic [BlockAw-1:0] SCMI_MESSAGE_PAYLOAD_30_C0_OFFSET = 8'h 94;
  parameter logic [BlockAw-1:0] SCMI_MESSAGE_PAYLOAD_31_C0_OFFSET = 8'h 98;
  parameter logic [BlockAw-1:0] SCMI_MESSAGE_PAYLOAD_32_C0_OFFSET = 8'h 9c;
  parameter logic [BlockAw-1:0] SCMI_DOORBELL_C0_OFFSET = 8'h a0;
  parameter logic [BlockAw-1:0] SCMI_COMPLETION_INTERRUPT_C0_OFFSET = 8'h a4;

  // Register index
  typedef enum int {
    SCMI_RESERVED_1_C0,
    SCMI_CHANNEL_STATUS_C0,
    SCMI_RESERVED_2_C0,
    SCMI_RESERVED_3_C0,
    SCMI_CHANNEL_FLAGS_C0,
    SCMI_LENGTH_C0,
    SCMI_MESSAGE_HEADER_C0,
    SCMI_MESSAGE_PAYLOAD_0_C0,
    SCMI_MESSAGE_PAYLOAD_1_C0,
    SCMI_MESSAGE_PAYLOAD_2_C0,
    SCMI_MESSAGE_PAYLOAD_3_C0,
    SCMI_MESSAGE_PAYLOAD_4_C0,
    SCMI_MESSAGE_PAYLOAD_5_C0,
    SCMI_MESSAGE_PAYLOAD_6_C0,
    SCMI_MESSAGE_PAYLOAD_7_C0,
    SCMI_MESSAGE_PAYLOAD_8_C0,
    SCMI_MESSAGE_PAYLOAD_9_C0,
    SCMI_MESSAGE_PAYLOAD_10_C0,
    SCMI_MESSAGE_PAYLOAD_11_C0,
    SCMI_MESSAGE_PAYLOAD_12_C0,
    SCMI_MESSAGE_PAYLOAD_13_C0,
    SCMI_MESSAGE_PAYLOAD_14_C0,
    SCMI_MESSAGE_PAYLOAD_15_C0,
    SCMI_MESSAGE_PAYLOAD_16_C0,
    SCMI_MESSAGE_PAYLOAD_17_C0,
    SCMI_MESSAGE_PAYLOAD_18_C0,
    SCMI_MESSAGE_PAYLOAD_19_C0,
    SCMI_MESSAGE_PAYLOAD_20_C0,
    SCMI_MESSAGE_PAYLOAD_21_C0,
    SCMI_MESSAGE_PAYLOAD_22_C0,
    SCMI_MESSAGE_PAYLOAD_23_C0,
    SCMI_MESSAGE_PAYLOAD_24_C0,
    SCMI_MESSAGE_PAYLOAD_25_C0,
    SCMI_MESSAGE_PAYLOAD_26_C0,
    SCMI_MESSAGE_PAYLOAD_27_C0,
    SCMI_MESSAGE_PAYLOAD_28_C0,
    SCMI_MESSAGE_PAYLOAD_29_C0,
    SCMI_MESSAGE_PAYLOAD_30_C0,
    SCMI_MESSAGE_PAYLOAD_31_C0,
    SCMI_MESSAGE_PAYLOAD_32_C0,
    SCMI_DOORBELL_C0,
    SCMI_COMPLETION_INTERRUPT_C0
  } scmi_id_e;

  // Register width information to check illegal writes
  parameter logic [3:0] SCMI_PERMIT [42] = '{
    4'b 1111, // index[ 0] SCMI_RESERVED_1_C0
    4'b 1111, // index[ 1] SCMI_CHANNEL_STATUS_C0
    4'b 1111, // index[ 2] SCMI_RESERVED_2_C0
    4'b 1111, // index[ 3] SCMI_RESERVED_3_C0
    4'b 1111, // index[ 4] SCMI_CHANNEL_FLAGS_C0
    4'b 1111, // index[ 5] SCMI_LENGTH_C0
    4'b 1111, // index[ 6] SCMI_MESSAGE_HEADER_C0
    4'b 1111, // index[ 7] SCMI_MESSAGE_PAYLOAD_0_C0
    4'b 1111, // index[ 8] SCMI_MESSAGE_PAYLOAD_1_C0
    4'b 1111, // index[ 9] SCMI_MESSAGE_PAYLOAD_2_C0
    4'b 1111, // index[10] SCMI_MESSAGE_PAYLOAD_3_C0
    4'b 1111, // index[11] SCMI_MESSAGE_PAYLOAD_4_C0
    4'b 1111, // index[12] SCMI_MESSAGE_PAYLOAD_5_C0
    4'b 1111, // index[13] SCMI_MESSAGE_PAYLOAD_6_C0
    4'b 1111, // index[14] SCMI_MESSAGE_PAYLOAD_7_C0
    4'b 1111, // index[15] SCMI_MESSAGE_PAYLOAD_8_C0
    4'b 1111, // index[16] SCMI_MESSAGE_PAYLOAD_9_C0
    4'b 1111, // index[17] SCMI_MESSAGE_PAYLOAD_10_C0
    4'b 1111, // index[18] SCMI_MESSAGE_PAYLOAD_11_C0
    4'b 1111, // index[19] SCMI_MESSAGE_PAYLOAD_12_C0
    4'b 1111, // index[20] SCMI_MESSAGE_PAYLOAD_13_C0
    4'b 1111, // index[21] SCMI_MESSAGE_PAYLOAD_14_C0
    4'b 1111, // index[22] SCMI_MESSAGE_PAYLOAD_15_C0
    4'b 1111, // index[23] SCMI_MESSAGE_PAYLOAD_16_C0
    4'b 1111, // index[24] SCMI_MESSAGE_PAYLOAD_17_C0
    4'b 1111, // index[25] SCMI_MESSAGE_PAYLOAD_18_C0
    4'b 1111, // index[26] SCMI_MESSAGE_PAYLOAD_19_C0
    4'b 1111, // index[27] SCMI_MESSAGE_PAYLOAD_20_C0
    4'b 1111, // index[28] SCMI_MESSAGE_PAYLOAD_21_C0
    4'b 1111, // index[29] SCMI_MESSAGE_PAYLOAD_22_C0
    4'b 1111, // index[30] SCMI_MESSAGE_PAYLOAD_23_C0
    4'b 1111, // index[31] SCMI_MESSAGE_PAYLOAD_24_C0
    4'b 1111, // index[32] SCMI_MESSAGE_PAYLOAD_25_C0
    4'b 1111, // index[33] SCMI_MESSAGE_PAYLOAD_26_C0
    4'b 1111, // index[34] SCMI_MESSAGE_PAYLOAD_27_C0
    4'b 1111, // index[35] SCMI_MESSAGE_PAYLOAD_28_C0
    4'b 1111, // index[36] SCMI_MESSAGE_PAYLOAD_29_C0
    4'b 1111, // index[37] SCMI_MESSAGE_PAYLOAD_30_C0
    4'b 1111, // index[38] SCMI_MESSAGE_PAYLOAD_31_C0
    4'b 1111, // index[39] SCMI_MESSAGE_PAYLOAD_32_C0
    4'b 1111, // index[40] SCMI_DOORBELL_C0
    4'b 1111  // index[41] SCMI_COMPLETION_INTERRUPT_C0
  };

endpackage

